config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    scope module: :projects do
      resources :tasks, except: [:index]
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  belongs_to :user

  validates :name, presence: true

  def percentage_complete
    return 0 if tasks.count.zero?

    (tasks.complete.count.to_f / tasks.count.to_f) * 100
  end

  def total_tasks_complete
    tasks.complete.count
  end

  def complete?
    status == 'complete'
  end

  def in_progress?
    status == 'in_progress'
  end

  def not_started?
    status == 'not_started'
  end

  def status
    return 'not_started' if (tasks.all?(&:not_started?) || tasks.count.zero?)
    return 'complete' if tasks.all?(&:complete?)

    'in_progress'
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  acts_as_list scope: :project

  enum status: {
    not_started: 'not_started',
    in_progress: 'in_progress',
    complete: 'complete'
  }

  validates :name, presence: true
  validates :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects/tasks_controller.rb
class Projects::TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:edit, :update, :destroy]

  def edit
  end

  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to(@task.project)
    else
      render action: :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to(@task.project)
    else
      render action: :edit
    end
  end

  def destroy
    @task.destroy

    redirect_to(@task.project)
  end

  private

  def set_project
    @project = current_user.projects.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :status, :project_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  def index
    @projects = current_user.projects.includes(:tasks).all
  end

  def show
    @task = @project.tasks.build
  end

  def new
    @project = current_user.projects.build
  end

  def edit
  end

  def create
    @project = current_user.projects.build(project_params)

    if @project.save
      redirect_to @project, notice: "Project was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: "Project was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project.destroy

    redirect_to projects_url, notice: "Project was successfully destroyed."
  end

  private

  def set_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(type)
    case type.to_sym
    when :notice
      'success'
    when :error
      'danger'
    else
      'primary'
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_badge_color(project)
    return 'secondary' if project.not_started?
    return 'success' if project.complete?

    'info'
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_class_color(task)
    return 'secondary' if task.not_started?
    return 'success' if task.complete?

    'info'
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, msg| %>
  <div class="alert alert-<%= alert_for(key) %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Simple PM", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Projects", projects_path, class: 'nav-link active', "aria-current": "page" %>
        </li>
      </ul>
      <form class="d-flex">
        <% if user_signed_in? %>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link active' %>
            </li>
          </ul>
        <% end %>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimplePm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/43ba35665e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render 'layouts/navbar' %>
    <div class="container pt-2">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary mt-2' %>
  </div>
<% end %>

app/views/projects/_task.html.erb
<div class="card mb-2">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <div class='task-status'>
        <i class="fas fa-grip-vertical grip text-secondary me-1"></i>
        <span class="badge bg-<%= task_class_color(task) %> mb-3"><%= task.status&.humanize %></span>
      </div>
      <div>
        <div class="dropdown float-start">
          <a class="btn btn-sm me-1 btn-outline-<%= task_class_color(task) %> dropdown-toggle" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            <%= task.status.humanize %>
          </a>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <% Task.statuses.keys.each do |status| %>
              <li>
                <a class="dropdown-item" href="#"
                  data-reflex="click->StatusReflex#change"
                  data-id="<%= task.id %>"
                  data-status="<%= status %>"
                >
                  <%= status.humanize %>
                </a>
              </li>
            <% end %>
          </ul>
        </div>
        <%= link_to edit_project_task_path(task.project, task), class: 'btn btn-sm btn-light' do %>
          <i class="far fa-edit"></i>
        <% end %>
        <%= link_to project_task_path(task.project, task), method: :delete,
                                                           data: { confirm: 'Are you sure?' },
                                                           class: 'btn btn-sm btn-dark' do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </div>
    </div>
    <h5 class="card-title mb-2">
      <span><%= task.name %></span>
    </h5>
    <p><%= task.description %></p>
  </div>
</div>

app/views/projects/edit.html.erb
<%= link_to 'Back', @project, class: 'btn btn-secondary mb-3' %>

<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>Editing Project</span>
    </h2>
    <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title d-flex justify-content-between mb-4">
      <span>Projects</span>
      <%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>
    </h2>

    <% @projects.each do |project| %>
      <%= link_to project, class: 'text-decoration-none' do %>
        <div class="card project-card mb-3">
          <div class="card-body">
            <div class="mb-3">
              <span class="badge bg-<%= project_badge_color(project) %> mb-3">
                <%= project.status.humanize %>
              </span>
              <span class="text-secondary">
                <small>
                  <%= number_to_percentage(project.percentage_complete, precision: 0) %> complete
                  (<%= project.total_tasks_complete %>/<%= project.tasks.count %>)
                </small>
              </span>
            </div>
            <h5 class="card-title text-dark"><b><%= project.name %></b></h5>
            <p class="text-secondary"><%= project.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<%= link_to 'Back', projects_path, class: 'btn btn-secondary mb-3' %>


<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>New Project</span>
    </h2>
    <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<%= link_to 'Back', projects_path, class: 'btn btn-secondary mb-3' %>

<div class="card">
  <div class="card-body">
    <h2 class="card-title d-flex justify-content-between mb-4">
      <span><%= @project.name %></span>
      <div>
        <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-light' %>
        <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-dark' %>
      </div>
    </h2>

    <div class="mb-4">
      <h6>Add task</h6>
      <%= form_with(model: [@task.project, @task]) do |f| %>
        <% if @task.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

            <ul>
            <% @task.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <%= f.hidden_field :status, value: :not_started %>

        <div class="input-group">
          <%= f.text_field :name, placeholder: 'Task name', class: 'form-control', autofocus: true %>
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %>

    </div>

    <h4>Not Started</h4>
    <div class="tasks-bg">
      <ul class="tasks-list" data-status="not_started" data-controller="tasks">
        <% @project.tasks.not_started.each do |task| %>
          <% if task.persisted? %>
            <li class="task-item" data-task-id="<%= task.id %>">
              <%= render 'projects/task', task: task %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <h4>In progress</h4>
    <div class="tasks-bg">
      <ul class="tasks-list" data-status="in_progress" data-controller="tasks">
        <% @project.tasks.in_progress.each do |task| %>
          <% if task.persisted? %>
            <li class="task-item" data-task-id="<%= task.id %>">
              <%= render 'projects/task', task: task %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <h4>Complete</h4>
    <div class="tasks-bg">
      <ul class="tasks-list" data-status="complete" data-controller="tasks">
        <% @project.tasks.complete.each do |task| %>
          <% if task.persisted? %>
            <li class="task-item" data-task-id="<%= task.id %>">
              <%= render 'projects/task', task: task %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/projects/tasks/_form.html.erb
<%= form_with(model: [@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, Task.statuses.keys.map { |s| [s.humanize, s] }, {}, class: 'form-select' %>
  </div>

  <br/>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/projects/tasks/_list.html.erb
<% tasks.each do |task| %>
  <% if task.persisted? %>
    <div class="card">
      <div class="card-body">
        <span class="badge bg-primary"><%= task.status&.humanize %></span>
        <h5 class="card-title d-flex justify-content-between mb-4">
          <span><%= task.name %></span>
          <div>
            <%= link_to 'Edit', edit_project_task_path(task.project, task), class: 'btn btn-sm btn-warning' %>
            <%= link_to 'Destroy', project_task_path(task.project, task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
          </div>
        </h5>
        <p><%= task.description %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/projects/tasks/edit.html.erb
<%= link_to 'Back', @project, class: 'btn btn-secondary mb-3' %>

<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>Editing Task</span>
    </h2>
    <%= render 'form' %>
  </div>
</div>